version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENSEARCH_URL=${OPENSEARCH_URL}
      - OPENSEARCH_USERNAME=${OPENSEARCH_USERNAME}
      - OPENSEARCH_PASSWORD=${OPENSEARCH_PASSWORD}
      - LLM_SERVICE_URL=${LLM_SERVICE_URL}
      - EMBEDDING_SERVICE_URL=${EMBEDDING_SERVICE_URL}
      - VECTOR_DB_TYPE=${VECTOR_DB_TYPE}
      - QDRANT_URL=${QDRANT_URL}
      - QDRANT_API_KEY=${QDRANT_API_KEY}
    depends_on:
      - opensearch
      - qdrant

  opensearch:
    image: opensearchproject/opensearch:latest
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9600:9600"

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"

  llm-service:
    image: vllm/vllm-openai:latest
    ports:
      - "8001:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  embedding-service:
    build:
      context: .
      dockerfile: Dockerfile
    command: python scripts/embedding_server.py
    ports:
      - "8002:8002"

